Fix/duplicate contacts webids
inrupt/pod-browser pull request #101
Opened 2020-10-05 09:50 UTC by VirginiaBalseiro

### Disallowing duplicate WebIDs to be added to contacts
- If the user tries to add a contact with a WbId that is already in the address book, an error will be displayed and the contact won't be added
- Added tests to the AddContact component

This PR fixes bug #.

- [x] I've added a unit test to test for potential regressions of this bug.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2020-10-05 15:41 UTC, megoth requested changes

2020-10-05 15:41 UTC, megoth commented on components/addContact/index.jsx
> +    const addressBookIri = joinPath(pod, "contacts/");
Use the hook `useAddressBook` instead, and use `getSourceUrl` from the Solid Client JS to get the url.

2020-10-05 15:41 UTC, megoth commented on components/addContact/index.jsx
> +      contact.fn =
Maybe lets use `fetchProfile` instead, so we have a "standard" way of handling names, in a prepared object.

2020-10-05 15:41 UTC, megoth commented on components/addContact/index.test.jsx
> +    getUrl.mockReturnValue("https://www.example.com/");
You shouldn't need to mock the return value here if you've used the mocking methods from the Solid Client JS.

2020-10-05 15:41 UTC, megoth commented on components/addContact/index.test.jsx
> +    getUrl.mockReturnValue("https://www.example.com/");
Again, these methods that don't do any fetch shouldn't be necessary, use the mocking methods from Solid Client properly instead.

2020-10-05 15:41 UTC, megoth commented on components/addContact/index.test.jsx
> +    const peopleDataset = mockSolidDatasetFrom(
Use `contactsContainerIri("https://www.example.com")` instead of hardcoding       `"https://www.example.com/contacts"`.

2020-10-06 14:30 UTC, megoth requested changes

2020-10-06 14:30 UTC, megoth commented on package-lock.json
> -    "@sentry/browser": {
Seems weird to have these changes in package-lock.json, when there are no changes in package.json. Sure this is right?

2020-10-06 16:09 UTC, megoth approved these changes

2020-10-06 16:16 UTC, ajacksified requested changes
I was able to add a duplicate. Can dig through the code to figure out why in a few - just want to block the approval.

Edit: tried again and it's fine.

2020-10-07 12:05 UTC, ajacksified approved these changes

2020-10-08 11:50 UTC, merged