Feat/hamburger menu
inrupt/pod-browser pull request #148
Opened 2020-10-27 16:03 UTC by VirginiaBalseiro

# Hamburger menu for small screens
In this PR:
- Slight refactor of the `header` component: `mainNav` is now its own component
- Added a hamburger menu only visible in small screens

### To test:
- Open Pod Browser, verify that the header still looks and work properly on desktop view
- Switch to mobile view, check that only the hamburger icon is visible in the header. 
- Click on the hamburger and verify that the links work properly

### Screenshots:
- Desktop:
![image](https://user-images.githubusercontent.com/28412960/97328272-26237e80-1876-11eb-8e63-b6643a32c854.png)

- Mobile:
![image](https://user-images.githubusercontent.com/28412960/97328328-363b5e00-1876-11eb-8ea6-475556d1822a.png)
![image](https://user-images.githubusercontent.com/28412960/97328361-3d626c00-1876-11eb-852f-e468c6e1e7c1.png)

# Checklist

- [x] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2020-10-27 16:22 UTC, megoth requested changes
A couple of fixes, but nothing big.

2020-10-27 16:22 UTC, megoth commented on components/header/mainNav/index.jsx
> +    <div className={classes.mainNav}>
for simplicity of reading, I would suggest only using one form of the result of useStyles, i.e. `classes.mainNav` --> `bem("mainNav")`.

2020-10-27 16:22 UTC, megoth commented on components/header/mainNav/index.jsx
> +    <div className={classes.mainNav}>
Or if you want to have those two forms, at least reuse classes in useBem instead of invoking useStyles again.

2020-10-27 16:22 UTC, megoth commented on components/header/menuDrawer/styles.js
> +      borderRadius: "0px 0px 10px 10px",
Lets use the borderRadius from the theme on this one, `theme.shape.borderRadius`. It corresponds to 4 by default, so you can you do `0 0 ${theme.shape.borderRadius * 2.5} ${theme.shape.borderRadius * 2.5}` instead.

2020-10-27 16:22 UTC, megoth commented on components/header/menuDrawer/styles.js
> +      borderRadius: "0px 0px 10px 10px",
(But I think we might just want to use the default border radius - check with @KyraAssaad whether it should stay consistent with theme properties, or if we want it to be 10px.

2020-10-27 16:22 UTC, megoth commented on components/header/menuDrawer/index.jsx
> +            <span
Maybe have an icon for Log out like we do on the desktop version?

2020-10-27 16:22 UTC, megoth commented on components/header/menuDrawer/index.jsx
> +            <span
@KyraAssaad ^ ?

2020-10-28 08:17 UTC, VirginiaBalseiro commented
@megoth I made all non-design related changes. For the icon in the logout option in the dropdown and the border radius, shall we have a separate discussion with @KyraAssaad and create the corresponding story if necessary?

2020-10-28 10:16 UTC, megoth commented
> @megoth I made all non-design related changes. For the icon in the logout option in the dropdown and the border radius, shall we have a separate discussion with @KyraAssaad and create the corresponding story if necessary?

I reckon improvements will be done through a more thorough review, so I think we can leave it as is for now.

2020-10-28 10:16 UTC, megoth approved these changes

2020-10-28 12:33 UTC, kevin-inrupt approved these changes

2020-10-28 12:57 UTC, merged