Fix/table row keyboard events
inrupt/pod-browser pull request #152
Opened 2020-10-28 12:42 UTC by VirginiaBalseiro

This PR fixes: 
- Contact and Files tables are not keyboard accessible

Table rows in Contacts and Files can now be accessed via keyboard and the details drawer is opened when Enter key is pressed.

- [x] I've added a unit test to test for potential regressions of this bug.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2020-10-28 12:46 UTC, ajacksified requested changes
This opens the drawer - but focus should be moved to the context menu so that the actions can be tabbed through as well.

2020-10-29 16:10 UTC, megoth requested changes
I'm not able to open the drawer for a contact using the enter key. It seems like the drawer closes right after it opens.

Maybe use `onKeyUp` instead?

2020-10-30 09:02 UTC, VirginiaBalseiro commented
> I'm not able to open the drawer for a contact using the enter key. It seems like the drawer closes right after it opens.
> 
> Maybe use `onKeyUp` instead?

Good catch! for whatever reason it was working for me locally but not on the Vercel preview 🤯 It should be fixed now!

2020-10-30 10:26 UTC, megoth approved these changes

2020-10-30 12:49 UTC, ajacksified approved these changes

2020-10-30 18:46 UTC, kevin-inrupt approved these changes

2020-11-02 08:10 UTC, merged