Fix: remove sharing & permissions link
inrupt/pod-browser pull request #162
Opened 2020-10-29 15:36 UTC by VirginiaBalseiro

This PR removes Sharing & Permissions button from the Details drawer.

- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2020-10-29 16:00 UTC, megoth requested changes
Please also remove the related code that is specific to the sharing accordion, e.g. sharingExpanded and setSharingExpanded.

2020-10-30 08:26 UTC, VirginiaBalseiro commented
> Please also remove the related code that is specific to the sharing accordion, e.g. sharingExpanded and setSharingExpanded.

@megoth Aren't those being used below by the Permissions accordion?

2020-10-30 10:22 UTC, megoth approved these changes
Just make sure to align package.json and package-lock.json, and you're good!

2020-10-30 12:44 UTC, ajacksified approved these changes

2020-10-30 12:45 UTC, kevin-inrupt approved these changes

2020-10-30 12:55 UTC, merged