WIP: refactoring to use index dataset
inrupt/pod-browser pull request #175
Opened 2020-11-05 14:44 UTC by VirginiaBalseiro

This PR fixes bug #.

- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] The changelog has been updated, if applicable.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

# New feature description

# Checklist

- [ ] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2020-11-06 10:08 UTC, megoth requested changes

2020-11-06 10:09 UTC, VirginiaBalseiro commented on components/contactsList/index.jsx
> +  // return <div>Boo</div>;
looool but they're funny though

2020-11-06 11:45 UTC, megoth requested changes

2020-11-06 11:45 UTC, megoth commented on src/addressBook/index.test.js
> +      .spyOn(solidClientFns, "getThingAll")
You don't need to mock `getThingAll`, but make sure to provide the dataset you need it to process.

To test the filter function, maybe insert a thing that isn't a `foaf:Person` as well.

2020-11-06 11:45 UTC, megoth commented on src/addressBook/index.test.js
> +      .spyOn(solidClientFns, "getThingAll")
Ditto (do not mock getThingAll).

2020-11-06 11:45 UTC, megoth commented on src/addressBook/index.test.js
> +    jest.spyOn(solidClientFns, "getSourceUrl").mockReturnValue(addressBookIri);
Don't mock `getSourceUrl`.

2020-11-06 11:45 UTC, megoth commented on src/addressBook/index.test.js
> +      .spyOn(addressBookFns, "createContact")
`createContact` isn't an asynchronous function that connects to the server, so you shouldn't need to mock it.

2020-11-06 11:45 UTC, megoth commented on src/addressBook/index.test.js
> +      .mockReturnValueOnce(updatedPeopleIndexDataset);
No need to mock `removeThing`.

2020-11-06 11:45 UTC, megoth commented on src/hooks/useContacts/index.test.jsx
> +      cleanup();
I think https://testing-library.com/docs/react-testing-library/api/#cleanup is added automatically? Sure you need it here?

2020-11-12 15:50 UTC, ajacksified reviewed
Looks good after test cleanup.

2020-11-13 10:40 UTC, megoth approved these changes

2020-11-16 08:12 UTC, merged