Feat: pod indicator reformat
inrupt/pod-browser pull request #201
Opened 2020-11-24 10:27 UTC by VirginiaBalseiro

# Pod indicator reformat

- Separate pod navigator into a component
- Style changes
- Tests updates

# Checklist

- [ ] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2020-11-24 13:53 UTC, megoth requested changes
We should translate px to the corresponding values in theme.spacing.

2020-11-24 13:53 UTC, megoth commented on components/containerPageHeader/styles.js
> +        paddingLeft: "24px",
Use the theme enabled spacing instead, e.g. `theme.spacing(2.4)` (I think default spacing is 10).

2020-11-24 13:53 UTC, megoth commented on components/podIndicator/podNavigatorPopover/styles.js
> +      borderRadius: "0 0 10px 10px",
Again, let's use the theme's spacing method: `theme.spacing(0, 0, 1, 1)`.

2020-11-24 13:53 UTC, megoth commented on components/podIndicator/styles.js
> +      padding: "6px 24px",
Use theme.spacing.

2020-11-24 13:53 UTC, megoth commented on components/podIndicator/styles.js
> +      fontSize: "13px",
I think we should use 0.825rem here, to stay consistent with other uses of small fonts.

2020-11-24 13:53 UTC, megoth commented on components/podIndicator/styles.js
> +        padding: `6px 40px 3px ${indicatorLabelPaddingLeft}px`,
Use theme.spacing

2020-11-24 13:53 UTC, megoth commented on components/podIndicator/styles.js
> +      borderRadius: "0 0 10px 10px",
Use theme.spacing

2020-11-24 13:53 UTC, megoth commented on components/podIndicator/styles.js
> +      padding: "0 8px",
Use theme.spacing

2020-11-24 14:27 UTC, megoth approved these changes
Just another slight change, and we're good; I'll approve it at once, so you can just mark it ready for QA when you're done.

2020-11-24 14:27 UTC, megoth commented on components/podIndicator/styles.js
> +      fontSize: theme.typography.subtitle2,
You should be more specific, i.e. `theme.typography.subtitle2.fontSize`.

2020-11-24 14:32 UTC, megoth approved these changes

2020-11-30 01:13 UTC, kevin-inrupt approved these changes

2020-11-30 08:57 UTC, merged