Feat: show policies
inrupt/pod-browser pull request #233
Opened 2021-01-15 10:30 UTC by VirginiaBalseiro

# Policies: show

**In this PR:** 

- create AddAgentButton, AgentAccessOptionsMenu, AgentAccessTable and AgentProfileDetails components

- refactor ResourceSharing (combine with AgentAccessList) and AgentAccess components

- Add tests

**Not in this PR:** 

- Mobile styles, as designs are not available yet. We have a ticket to have the drawer cover the bottom half of the screen which will ameliorate some of the problems with these designs on small screens.

**Assumptions and caveats:**

- This PR assumes that we will continue to use normalized permissions

- The filtering by type (tabs) will obviously change since groups will likely not have a profile with a types array, it is just functioning as a placeholder for now.

# Checklist

- [x] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2021-01-18 14:00 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
> +    acl: {
I think `createAccessMap()` is favorable to make the code easier to read (gets very noisy if you keep repeating the map)

2021-01-18 14:00 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
> +            read: true,
Use createAccessMap()

2021-01-18 14:00 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
> +            read: true,
Use createAccessMap()

2021-01-18 14:00 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
> +            read: true,
Use createAccessMap()

2021-01-18 14:00 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
> +            read: true,
Use createAccessMap()

2021-01-18 14:00 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
> +            read: true,
Use createAccessMap()

2021-01-18 14:00 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
> +            read: true,
Use createAccessMap()

2021-01-18 14:01 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
> +            read: true,
Use createAccessMap()

2021-01-18 14:05 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/index.test.jsx
> +        read: true,
Use createAccessMap()

2021-01-18 14:07 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/index.test.jsx
> +        read: true,
Use createAccessMap()

2021-01-18 14:07 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/index.test.jsx
> +        read: true,
Use createAccessMap()

2021-01-18 14:07 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/index.test.jsx
> +        read: true,
Use createAccessMap()

2021-01-18 14:08 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/index.test.jsx
> +              read: true,
Use createAccessMap()

2021-01-18 14:08 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/index.test.jsx
> +              read: true,
Use createAccessMap()

2021-01-18 14:08 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/index.test.jsx
> +              read: true,
Use createAccessMap()

2021-01-18 14:09 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      borderRadius: "4px",
Use `theme.shape.borderRadius` instead.

2021-01-18 14:10 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      fontSize: "12px",
Again, think this can be nudged to 13px, to keep the small font-sizes consistent?

2021-01-18 14:10 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      borderRadius: "4px",
Use `theme.shape.borderRadius`

2021-01-18 14:10 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      border: "1px solid #D8D8D8",
Can we nudge the color onto one of the existing gray colors? https://prism.inrupt.vercel.app/?path=/story/themes-sdk-default--page

2021-01-18 14:13 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      fontSize: "22px",
This is the same font size as H1; should we reuse that variable? (i.e. `theme.typography.h1.fontSize`)

2021-01-18 14:18 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      color: "#2196F3",
I reckon these colors don't need to formalized into the theme? But I reckon we might want to formalize them into something more specific to the role these parts play?

This is more of a question to @KyraAssaad, let's ask her when she's back what she think we should do in this case.

2021-01-18 14:19 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      borderBottom: "1px solid #D8D8D8",
Again, can we reuse a gray color?

2021-01-18 14:19 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      height: "40px",
Magical value - can this be turned into some REM or EM value instead?

2021-01-18 14:20 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      borderRadius: "10px",
Is the 10px for borderRadius something we want to formalize as well?

2021-01-18 14:21 UTC, megoth commented on components/resourceDetails/resourceSharing/agentAccessTable/styles.js
> +      fontSize: "14px",
Another font size? (We now have 10, 12, 13, and 14). Let's nudge this toward 13px? (And again, you can simply write the number 13 instead of "13px")

2021-01-21 14:47 UTC, megoth requested changes
Looking very good! With the addition of feature flags this will be complete ^_^

2021-01-25 18:26 UTC, megoth approved these changes

2021-01-25 18:26 UTC, megoth commented
@VirginiaBalseiro just needs updating the snapshot, and I think this PR should be good.

2021-01-26 17:14 UTC, kevin-inrupt approved these changes

2021-01-27 13:34 UTC, merged