Fix/requesting dataset twice
inrupt/pod-browser pull request #282
Opened 2021-04-08 08:12 UTC by VirginiaBalseiro

This PR fixes bug where every resource was requested twice. 

The bug was caused by a hook that fetched the IRIs for the resources within a container. Instead of using the dataset directly, it was fetching the dataset again, and then fetching the IRIs. 

Since we already do a GET request for the dataset itself before fetching the IRIs for the resources, it made more sense to use the dataset directly, so I created a container model and we now use the model in the Container view component and the function that fetches the IRIs. 

- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2021-04-08 08:35 UTC, megoth requested changes

2021-04-08 08:35 UTC, megoth commented on components/container/index.test.jsx
>        error: { message: "500" },
Let's improve this slightly by doing `error: new Error("500")` instead.

2021-04-08 08:35 UTC, megoth commented on components/container/index.test.jsx
>        error: { message: "500" },
Same with the other cases of `{ message: --- }`

2021-04-08 08:35 UTC, megoth commented on components/container/index.test.jsx
> +      data: { dataset: mockSolidDatasetFrom(resourceIri) },
You're creating very specific objects that only has the properties you need for this test - you should instead create mocked objects of models (with functions that can be reused elsewhere).

For example, we could have a factory method that takes the URL of the thing you want, which mocks a thing and dataset (which you must strip the hash-part of the URL, if any) for you based on that one URL.

2021-04-08 09:17 UTC, megoth approved these changes

2021-04-08 09:17 UTC, megoth commented on src/models/container/index.js
> +export function getContainerResourceIris({ thing }) {
Let's follow the same naming convention as the Solid Client library, i.e. `getContainerResourceUrlAll`

2021-04-19 14:36 UTC, ajacksified approved these changes
Nice work!

2021-04-19 23:01 UTC, kevin-inrupt approved these changes

2021-04-20 06:49 UTC, merged