Feat: privacy page
inrupt/pod-browser pull request #305
Opened 2021-07-06 12:03 UTC by VirginiaBalseiro

# Feat: privacy page

- Add a Privacy page which displays contacts (people) and apps
  - I decided to keep the Contacts page as it is today and create a new Privacy page which essentially displays the contacts well. This is to make the conditional rendering easier and to start migrating from contacts to audit list more gradually, but this page reuses a lot of the Contacts page components and functionality for now.

- Add the privacy page to feature flag

- Make AgentTabs more generic so they can be reused throughout the app

- Add tests

Note: Prism version needs to be updated to a proper patch before merging

# Checklist

- [x] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2021-07-06 14:37 UTC, kevin-inrupt approved these changes
Privacy page displayed appropriately for different users.

2021-07-07 12:17 UTC, ajacksified requested changes
Try to clean up as many of the linter warnings as possible; I know some are from commented tests, although I'd think it.skip would be good enough rather than commenting them out.

2021-07-07 12:17 UTC, ajacksified commented on components/agentList/index.jsx
> +// termporarily using mock data for apps for dev purposes until we have audit list
```suggestion
// FIXME: temporarily use mock data for apps for dev purposes until we have audit list
```

"FIXME" makes searching the codebase for things we forgot easier.

2021-07-07 12:17 UTC, ajacksified commented on components/pages/privacy/index.jsx
> +      value: "app", // this string for now until we define what type the app contact will be
Same here and below at line 61:

```suggestion
      // FIXME: replace with app contact type iri
      value: "app", // this string for now until we define what type the app contact will be
```

You may also want to make "app" a constant to make it easy to refactor later.

2021-07-07 12:17 UTC, ajacksified commented on components/pages/privacy/index.test.jsx
> +import { fireEvent, render, waitFor } from "@testing-library/react";
Some linter warnings below.

2021-07-08 16:16 UTC, KyraAssaad approved these changes
It works and it looks great!

2021-07-09 12:05 UTC, ajacksified approved these changes

2021-07-09 12:47 UTC, merged