Feature/consent request form UI
inrupt/pod-browser pull request #315
Opened 2021-07-26 19:52 UTC by norbert989

# Consent request form UI

Added styling and markup for the consent request form.

- To test this log in to PB
- Navigate to the Privacy Page
- Click the bottom left mock link

TODO: Add missing icons to prism and update as part of the logic implementation ticket
# Checklist

- [x] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2021-07-27 07:47 UTC, VirginiaBalseiro requested changes
Might be worth populating the request page with mock data based on the API doc instead of hard coding strings (might need updating later but we can have a rough idea of what the consent request would look like).

Also adding some tests for the interactions even if for now is just checking that a handler is called.

2021-07-27 07:52 UTC, VirginiaBalseiro commented
Also, why did you choose [rid] instead of just [id] for the consent id in the Consent Show page?

2021-07-27 08:14 UTC, VirginiaBalseiro reviewed
Left a couple comments

2021-08-02 07:55 UTC, VirginiaBalseiro requested changes
Nice work! Just left a few comments.

2021-08-02 07:55 UTC, VirginiaBalseiro commented on components/pages/privacy/consent/requests/styles.js
> +      flexGrow: "1",
This doesn't need to be a string.

2021-08-02 07:55 UTC, VirginiaBalseiro commented on components/pages/privacy/consent/requests/styles.js
> +      margin: "0",
Same here, this should be a number.

2021-08-02 07:55 UTC, VirginiaBalseiro commented on components/pages/privacy/consent/requests/styles.js
> +      fontSize: 16,
16 is the default, so I think this is not needed. In any case 1rem should result in 16.

2021-08-02 07:55 UTC, VirginiaBalseiro commented on components/pages/privacy/consent/styles.js
> +      flexGrow: "1",
Same here, this should be a number.

2021-08-02 07:55 UTC, VirginiaBalseiro commented on components/pages/privacy/consent/styles.js
> +      margin: "0",
Same here, this should be a number.

2021-08-02 07:55 UTC, VirginiaBalseiro commented on components/pages/privacy/consent/styles.js
> +      fontSize: 16,
Same as above.

2021-08-02 07:55 UTC, VirginiaBalseiro commented on components/consentRequestForm/styles.js
> +      flexGrow: "1",
This doesn't need to be a string, should be a number.

2021-08-02 07:55 UTC, VirginiaBalseiro commented on components/consentRequestForm/styles.js
> +      margin: "0",
Same here, this should be a number.

2021-08-03 09:38 UTC, VirginiaBalseiro approved these changes
One tiny thing was left from previous review

2021-08-03 09:38 UTC, VirginiaBalseiro commented on components/consentRequestForm/styles.js
> +      flexGrow: "1",
This one seems to be unresolved

2021-08-04 11:06 UTC, VirginiaBalseiro approved these changes

2021-08-05 13:20 UTC, kevin-inrupt approved these changes

2021-08-05 14:05 UTC, merged