Feature/agent access resource path
inrupt/pod-browser pull request #346
Opened 2021-09-13 10:22 UTC by norbert989

# Added resource path for nested folders/files

# Checklist

- [x] All acceptance criteria are met.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2021-09-13 17:09 UTC, KyraAssaad requested changes
Ahah...ha...ha.... I broke it 😁 

![Inrupt_PodBrowser](https://user-images.githubusercontent.com/11729241/133125906-ce179914-fb88-4b5b-9307-1a5b2d60e1ec.png)

Changes:
1. Let's make the Name column have a max-width of 650px. 
2. In the case that it overflows, we should prioritize displaying the name of the resource, and truncate the rest of the path with ellipses. For example, it would look like "...[name of resource]". In the event that even the name of the resource is too long to fit 650px, then the front of the name should be truncated and the end of the name should be displayed
3. In the sidebar, let's wrap the name of the path the same way we wrap the name of the resource
4. Is it possible to remove the HTML spaces conversion from the path, so we don't get the %20 cluttering up the names?
5. Can we also please top align the resource icon with the name of the resource
![Inrupt_PodBrowser](https://user-images.githubusercontent.com/11729241/133126919-4bf8aacd-fcd4-41fe-9c62-97ad3946818e.png)

2021-09-14 12:18 UTC, VirginiaBalseiro approved these changes

2021-09-14 15:15 UTC, KyraAssaad approved these changes
You did it! Nicely done.

2021-09-15 16:24 UTC, kevin-inrupt approved these changes

2021-09-16 08:12 UTC, merged