Feat: revoke all access
inrupt/pod-browser pull request #348
Opened 2021-09-28 15:57 UTC by VirginiaBalseiro

# Agent auditing: revoke all access

In this PR: 
- Revoke All Access button
- Refactoring the existing revoke access button(s) so that we have only one that we re-use throughout the audit list
- Splitting TabPanel into its own file
- Adding missing tests to:
  - Resource Access Show page
  - Tab Panel
  - Revoke Access Button

_Note: for lack of time I had to ignore some lines from coverage, I will add tests for those once we focus on Auditing again._

# Checklist

- [x] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2021-09-28 21:40 UTC, KyraAssaad requested changes
A few changes please: 

1. The title of the modal should be "Revoke access **from** ${agentName}?'

(see https://www.sketch.com/s/f073950c-60f8-47d1-9d8f-4824de19ba08/a/Vr8OYqo)

2. The body text should say '${agentName] will not be able to access **anything** in your **P**od.'

3. The button should say 'Revoke All Access' - I saw you added a unit test for this but it didn't seem to work

![Inrupt_PodBrowser](https://user-images.githubusercontent.com/11729241/135168982-8296dbd4-850e-4be6-aab3-e94fa3118ee9.png)

4. When you click on the 'Revoke All Access' button in the confirmation modal, we should redirect the user back to the main Privacy page

5. When we have redirected the user back to the main privacy page, the agent that you just removed access for shouldn't show up in the list anymore. I know they are still showing up because they have public or authenticated access, but that's a different problem that we'll address later. For now if it is possible to remove the person completely from the list, that would be great. 

6. Please increase the Revoke All Access link below the resource table size 16px (right now it is 13.33333px)

Thanks :)

2021-09-28 21:40 UTC, KyraAssaad commented on components/pages/privacy/resourceAccess/resourceAccessDrawer/index.jsx
> -    setTitle(`Revoke access to ${resourceName}`);
Can we please add a question mark at the end of this, so it says 'Revoke access to ${resourceName}?'

2021-09-29 12:50 UTC, ajacksified requested changes

2021-09-29 12:50 UTC, ajacksified commented on components/pages/privacy/resourceAccess/revokeAccessButton/index.jsx
> +      : "anything in your pod";
It'd be nice to have all of these strings as constants - that will make it easier to swap them out for localized strings later.

2021-10-05 15:18 UTC, ajacksified approved these changes

2021-10-05 16:30 UTC, kevin-inrupt approved these changes

2021-10-06 06:47 UTC, merged