Feat: redirect user to main page if not data subject of access request
inrupt/pod-browser pull request #471
Opened 2022-04-06 16:42 UTC by VirginiaBalseiro

## Description

- add check for resource owner WebID and redirect/display alert

- update tests and mock access requests

## Testing
- go to https://test-app-access-grants.vercel.app/
- generate a request
- make sure you are logged in to PB with a WebId that is different from the resource owner you inputted on the demo app to generate the request
- once redirected, grab the section of the URL starting from privacy/...
- go to the Vercel deployment of this PR and append that to the URL
- verify a red toast is displayed and you are redirected to the main PB page
- log out of PB and log in as the resource owner
- navigate to the request page again (use the same one you used before)
- verify you can see the request and everything works as intended

## Commit checklist

- [x] All acceptance criteria are met.
- [ ] Includes tests to ensure functionality and prevent regressions.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.

2022-04-06 19:33 UTC, KyraAssaad requested changes
Ok, I think I followed the instructions, BUT when I tried to login on https://pod-browser-git-feat-access-request-resource-owner-hide-inrupt.vercel.app/ with the correct resource owner, I am also getting the access denied message. 

Maybe some one else can try it out and see if it works for them and I'm just not doing it correctly?

2022-04-06 19:33 UTC, KyraAssaad commented on components/consentRequestForm/index.jsx
> +    alertError("You don't have access to that.");
Can we remove the period at the end please?

2022-04-07 15:03 UTC, KyraAssaad approved these changes

2022-04-08 12:19 UTC, ajacksified approved these changes

2022-04-08 12:44 UTC, merged

2022-04-08 12:45 UTC, solid-akb reviewed
Looks good!